### ISSUE TITLE
Server refused connection error, Can u help solving this>

### ISSUE THREAD

**Issue by searchformyusername** [henrymbuguak/imdb-movies-django-2-clone#1]
django.db.utils.OperationalError: could not connect to server: Connection refused (0x0000274D/10061)
        Is the server running on host "127.0.0.1" and accepting
        TCP/IP connections on port 5432?

**Comment by henrymbuguak** [comment]
Hello DEFEAT, 

The error basically means you are not able to connect to your database. In settings.py file ensure you configure your database correctly.

[Django Database configuration](https://docs.djangoproject.com/en/2.2/ref/databases/)

**Comment by searchformyusername** [comment]
Thankyou sir, I tried to debug it and found the same. I don't had PostgreSQL installed it was the issue. :) Thankyou.
